# NOTE: update this with your service name
service: resourcehub

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-west-2
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    tableName: posts

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:us-west-2:*:*"

functions:
  # Name of function defines service in serverless framework
  create:
  # Which javascript file and function are handling this
    handler: create.main
  # What events it responds to
    events:
      - http:
      # ourapiurl/posts 
          path: posts
      # HTTP Verb, POST in this case.
          method: post
          authorizer: aws_iam
  get:
    handler: get.main
    events:
      - http:
          path: posts/{id}
          method: get
          authorizer: aws_iam
  randomget:
    handler: randomget.main
    events:
      - http:
          path: posts/random
          method: get
          authorizer: aws_iam
  list:
    handler: list.main
    events:
      - http:
          path: posts
          method: get
          authorizer: aws_iam
  update:
    handler: update.main
    events:
      - http:
          path: posts/{id}
          method: put
          authorizer: aws_iam
  delete:
    handler: delete.main
    events:
      - http:
          path: posts/{id}
          method: delete
          authorizer: aws_iam